export { default as Connect } from './Connect';
export { default as Main } from './Main';
export { default as Discover } from './Discover';
export { default as FeaturedProperties } from './FeaturedProperties';
export { default as Footer } from './Footer';
export { default as OurServices } from './OurServices';
export { default as PeopleSection } from './PeopleSection';
export { default as Navbar } from './Navbar';
export { default as SearchFilters } from './SearchFilters';
